### ISSUE TITLE
Question about the requirements

### ISSUE THREAD

**Issue by hectoorperezz** [giorgosfatouros/DeepVaR#2]
I have a problem with the deepar function of the gluonts package. In the requirements.txt there isn´t this library and when I install it on my own the notebook gives me a problem with the Deepar function

**Comment by giorgosfatouros** [comment]
Which was the error?
with GluonTS==0.11.3 should work.

**Comment by hectoorperezz** [comment]
Okeyy I will try 0.11.3, thanks. You did an amazing work, it has to be said.

**Comment by hectoorperezz** [comment]
![jupyter](https://user-images.githubusercontent.com/132518548/236254596-e8d3a905-64f2-4020-a6d2-e071091db475.PNG)

I don´t understand this error. Shouldn´t be mxnet include i the GluonTS library?

**Comment by hectoorperezz** [comment]
Problem solved with Colab

**Comment by MaryamFeyzollahi** [comment]
You need to install mxnet. 
!pip install mxnet
